### ISSUE TITLE
Remote event on tick

### ISSUE THREAD

**Issue by Dadadah** [vugi99/onset-construction#3]
Currently the construction package will send remote event "UpdateCons" on tick from client to server. This is expensive. This function is for controlling the ghost of the construction, and this may be able to be done client side. Attached is some sample code that allows movement of the construction on the client side.

```
GetObjectStaticMeshComponent(object):SetMobility(EComponentMobility.Movable)
GetObjectActor(object):SetActorLocation(FVector(x,y,z))
```

**Comment by vugi99** [comment]
https://github.com/vugi99/onset-construction/commit/068aae33aca1571f3ebdf0a0325dcfcdddccfb76
